version: "3"

services:
    frontend:
        container_name: qm-frontend
        build:
            context: ./frontend
            dockerfile: Dockerfile
        depends_on:
            - backend
        ports:
            - "3000:81"
    backend:
        container_name: qm-backend
        build:
            context: ./backend
            dockerfile: Dockerfile
        ports:
            - "5143:80"