version: "3"

services:
    frontend:
        image: "node:latest"
        container_name: qm-frontend
        build: ./frontend
        depends_on:
            backend: 
                condition: service_healthy
        networks:
            - fe
        ports:
            - "3000:81"
    backend:
        image: "mcr.microsoft.com/dotnet/aspnet:8.0"
        container_name: qm-backend
        build: ./backend/app
        networks:
            - fe
            - be
        ports:
            - "5143:80"
    
networks:
    fe:
        ipam:
            driver: default
            config:
                - subnet: "192.168.1.0/24"
    be:
        ipam:
            driver: default
            config:
                - subnet: "192.168.2.0/24"
