version: "3"

services:
    frontend:
        container_name: qm-frontend
        build:
            context: ./frontend
            dockerfile: Dockerfile
        depends_on:
            - backend
        ports:
            - "3000:81"
    backend:
        container_name: qm-backend
        build:
            context: ./backend
            dockerfile: Dockerfile
        networks:
            - fe
            - be
        ports:
            - "5143:80"
    
networks:
    fe:
        ipam:
            driver: default
            config:
                - subnet: "192.168.1.0/24"
    be:
        ipam:
            driver: default
            config:
                - subnet: "192.168.2.0/24"
